version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "14"